nm = input("Please enter your name: ")
tp = input("Please enter your TP number: ")
mk = input("Please enter your marks: ")
grd = input("Please enter your grade: ")
cgpa = input("Please enter your CGPA: ")
print(f"Your details are as follows: \nName: {nm} \nTP Number: {tp} \nMarks: {mk} \nGrade: {grd} \nCGPA: {cgpa} \nThanks for registration")